import Head from 'next/head'
import Image from 'next/image'
import EducationLoan from '../components/Messages/EducationLoan'
import Navbar from '../components/Navbar/Navbar'
import AOS from 'aos'
import "aos/dist/aos.css";
import Banner from '../components/Banner'
import HomeSlider from '../components/Sliders/HomeSlider'

export default function Home() {
  return (
    <div className='min-w-screen font-poppins' >
      <Head>
        <title>Networkers Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<EducationLoan/>
<Navbar/>
<Banner/>
<div className='mt-[100px]'>

<HomeSlider/>
</div>
   
    </div>
  )
}
